version: '3.8'

services:
  cliente:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  php8.2:
    container_name: 'modular-php-8.2'
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
    volumes:
      - ./server/app:/var/www/html
      - ./server/config/php.ini:/usr/local/etc/php/php.ini
      - ./server/logs:/var/www/logs
      - ./server/config/sites-available:/etc/apache2/sites-available
    working_dir: /var/www/html
    networks:
      - modularLan
      - modular

  composer:
    container_name: 'modular-mycomposer'
    image: composer:2
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    tty: true
    command: '/bin/bash'
    networks:
      - modularLan
      - modular

  mariadb:
    container_name: 'modular-mariadb'
    image: mariadb:latest
    ports:
      - "3307:3306"
    volumes:
      - ./server/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Modular
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - modularLan
      - modular

  phpmyadmin:
    container_name: modular-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    hostname: phpmyadmin
    ports:
      - "8002:80"
    environment:
      PMA_HOST: modular-mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: modular
    networks:
      - modularLan
      - modular

networks:
  modularLan:
    internal: true
  modular:
    driver: bridge

